import { afterEach, beforeEach, describe, expect, test } from "bun:test";
import type { Client } from "pg";
import type { MigrationPlan } from "../../types/migration";
import type { Table } from "../../types/schema";
import {
  cleanDatabase,
  createTestClient,
  createTestSchemaService,
} from "../utils";
import {
  createColumnTestServices,
  executeColumnMigration,
  findColumn,
} from "./column-test-utils";

describe("PostgreSQL identity columns", function () {
  let client: Client;
  const services = createColumnTestServices();

  beforeEach(async function () {
    client = await createTestClient();
    await cleanDatabase(client);
  });

  afterEach(async function () {
    await cleanDatabase(client);
    await client.end();
  });

  async function planSchema(schema: string): Promise<MigrationPlan> {
    const current = await services.inspector.getCurrentSchema(client);
    const desired = await services.parser.parseCreateTableStatements(schema);
    return services.differ.generateMigrationPlan(desired, current);
  }

  test("parses modes, names, defaults, descending ranges, and bigint values", async function () {
    const tables = await services.parser.parseCreateTableStatements(`
      CREATE TABLE public.identity_parser_probe (
        implicit_bigint bigint GENERATED ALWAYS AS IDENTITY,
        custom smallint GENERATED BY DEFAULT AS IDENTITY (
          SEQUENCE NAME public.custom_identity_sequence
          START WITH 10
          INCREMENT BY 5
          MINVALUE 10
          MAXVALUE 1000
          CACHE 20
          CYCLE
        ),
        descending integer GENERATED ALWAYS AS IDENTITY (
          INCREMENT BY -2 NO MINVALUE NO MAXVALUE NO CYCLE
        ),
        precise bigint GENERATED ALWAYS AS IDENTITY (
          START WITH 9007199254740993
          MINVALUE -9223372036854775808
          MAXVALUE 9223372036854775807
        )
      );
    `);

    expect(tables[0]?.columns).toEqual([
      {
        name: "implicit_bigint",
        type: "INT8",
        nullable: false,
        default: undefined,
        identity: {
          generation: "ALWAYS",
          start: "1",
          increment: "1",
          minValue: "1",
          maxValue: "9223372036854775807",
          cache: "1",
          cycle: false,
        },
        generated: undefined,
      },
      {
        name: "custom",
        type: "INT2",
        nullable: false,
        default: undefined,
        identity: {
          generation: "BY DEFAULT",
          sequenceName: { schema: "public", name: "custom_identity_sequence" },
          start: "10",
          increment: "5",
          minValue: "10",
          maxValue: "1000",
          cache: "20",
          cycle: true,
        },
        generated: undefined,
      },
      {
        name: "descending",
        type: "INT4",
        nullable: false,
        default: undefined,
        identity: {
          generation: "ALWAYS",
          start: "-1",
          increment: "-2",
          minValue: "-2147483648",
          maxValue: "-1",
          cache: "1",
          cycle: false,
        },
        generated: undefined,
      },
      {
        name: "precise",
        type: "INT8",
        nullable: false,
        default: undefined,
        identity: {
          generation: "ALWAYS",
          start: "9007199254740993",
          increment: "1",
          minValue: "-9223372036854775808",
          maxValue: "9223372036854775807",
          cache: "1",
          cycle: false,
        },
        generated: undefined,
      },
    ]);
  });

  test("creates both identity modes with exact sequence options and stays idempotent", async function () {
    const schema = `
      CREATE TABLE public.identity_orders (
        id bigint GENERATED ALWAYS AS IDENTITY (
          START WITH 10 INCREMENT BY 5 MINVALUE 10 MAXVALUE 1000 CACHE 2 NO CYCLE
        ) PRIMARY KEY,
        external_id integer GENERATED BY DEFAULT AS IDENTITY,
        label text NOT NULL
      );
    `;

    await executeColumnMigration(client, schema, services);

    const inserted = await client.query(
      "INSERT INTO public.identity_orders (label) VALUES ('first') RETURNING id, external_id"
    );
    expect(inserted.rows[0]).toEqual({ id: "10", external_id: 1 });

    const explicitDefault = await client.query(
      "INSERT INTO public.identity_orders (external_id, label) VALUES (900, 'external') RETURNING id, external_id"
    );
    expect(explicitDefault.rows[0]).toEqual({ id: "15", external_id: 900 });

    await expect(
      client.query(
        "INSERT INTO public.identity_orders (id, label) VALUES (100, 'forbidden')"
      )
    ).rejects.toThrow(/OVERRIDING SYSTEM VALUE|generated always|non-DEFAULT value/i);

    const inspected = await services.inspector.getCurrentSchema(client);
    const table = inspected.find(function findTable(candidate) {
      return candidate.name === "identity_orders";
    });
    expect(findColumn(table!.columns, "id")?.identity).toEqual({
      generation: "ALWAYS",
      sequenceName: { schema: "public", name: "identity_orders_id_seq" },
      sequencePersistence: "logged",
      start: "10",
      increment: "5",
      minValue: "10",
      maxValue: "1000",
      cache: "2",
      cycle: false,
    });
    expect(findColumn(table!.columns, "external_id")?.identity?.generation).toBe(
      "BY DEFAULT"
    );

    const secondPlan = await planSchema(schema);
    expect(secondPlan.hasChanges).toBe(false);
  });

  test("keeps identity-owned sequences out of standalone sequence reconciliation", async function () {
    const schema = `
      CREATE TABLE public.identity_service (
        id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        label text NOT NULL
      );
    `;
    const schemaService = createTestSchemaService();

    const first = await schemaService.apply(schema, ["public"], true);
    const second = await schemaService.apply(schema, ["public"], true);

    expect(first.hasChanges).toBe(true);
    expect(second.hasChanges).toBe(false);
    expect(
      (
        await client.query(
          "SELECT to_regclass('public.identity_service_id_seq') AS sequence_name"
        )
      ).rows[0].sequence_name
    ).toBe("identity_service_id_seq");
  });

  test("parses explicit identity-sequence persistence", async function () {
    const parsed = await services.parser.parseSchema(`
      CREATE TABLE public.identity_persistence_parse (
        unlogged_id bigint GENERATED ALWAYS AS IDENTITY (UNLOGGED),
        logged_id bigint GENERATED BY DEFAULT AS IDENTITY (LOGGED)
      );
    `);

    expect(findColumn(parsed.tables[0]!.columns, "unlogged_id")?.identity)
      .toMatchObject({ sequencePersistence: "unlogged" });
    expect(findColumn(parsed.tables[0]!.columns, "logged_id")?.identity)
      .toMatchObject({ sequencePersistence: "logged" });
  });

  test("adds identity semantics to an existing populated column without replacing it", async function () {
    await client.query(`
      CREATE TABLE public.identity_existing (
        id integer,
        label text NOT NULL
      );
      INSERT INTO public.identity_existing (id, label) VALUES (50, 'preserved');
    `);

    const schema = `
      CREATE TABLE public.identity_existing (
        id integer GENERATED BY DEFAULT AS IDENTITY (
          SEQUENCE NAME public.identity_existing_custom_seq
          START WITH 100 INCREMENT BY 3 MINVALUE 1 MAXVALUE 10000 CACHE 1 NO CYCLE
        ),
        label text NOT NULL
      );
    `;
    const plan = await planSchema(schema);
    const sql = plan.transactional.join("\n");
    expect(sql.indexOf('ALTER COLUMN "id" SET NOT NULL')).toBeLessThan(
      sql.indexOf('ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY')
    );
    expect(sql).toContain('ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY');
    expect(sql).not.toContain('DROP COLUMN "id"');

    await services.executor.executePlan(client, plan, true);
    const rows = await client.query(
      "SELECT id, label FROM public.identity_existing ORDER BY id"
    );
    expect(rows.rows).toEqual([{ id: 50, label: "preserved" }]);

    const inserted = await client.query(
      "INSERT INTO public.identity_existing (label) VALUES ('generated') RETURNING id"
    );
    expect(inserted.rows[0].id).toBe(100);
    const inspected = await services.inspector.getCurrentSchema(client);
    const table = inspected.find(function findTable(candidate) {
      return candidate.name === "identity_existing";
    });
    expect(findColumn(table!.columns, "id")?.identity?.sequenceName).toEqual({
      schema: "public",
      name: "identity_existing_custom_seq",
    });
    expect((await planSchema(schema)).hasChanges).toBe(false);
  });

  test("adds a new identity column to populated rows using PostgreSQL backfill semantics", async function () {
    await client.query(`
      CREATE TABLE public.identity_backfill (label text NOT NULL);
      INSERT INTO public.identity_backfill (label) VALUES ('one'), ('two'), ('three');
    `);

    const schema = `
      CREATE TABLE public.identity_backfill (
        label text NOT NULL,
        id integer GENERATED ALWAYS AS IDENTITY (
          START WITH 50 INCREMENT BY 2 MINVALUE 1 MAXVALUE 1000 CACHE 1 NO CYCLE
        )
      );
    `;
    const plan = await planSchema(schema);
    expect(plan.transactional.join("\n")).toContain(
      'ADD COLUMN "id" INT4 GENERATED ALWAYS AS IDENTITY'
    );

    await services.executor.executePlan(client, plan, true);
    const rows = await client.query(
      "SELECT id, label FROM public.identity_backfill ORDER BY id"
    );
    expect(rows.rows).toEqual([
      { id: 50, label: "one" },
      { id: 52, label: "two" },
      { id: 54, label: "three" },
    ]);
    expect((await planSchema(schema)).hasChanges).toBe(false);
  });

  test("alters generation and sequence configuration without dropping state or data", async function () {
    const initialSchema = `
      CREATE TABLE public.identity_updates (
        id integer GENERATED BY DEFAULT AS IDENTITY (
          START WITH 10 INCREMENT BY 5 MINVALUE 10 MAXVALUE 1000 CACHE 1 NO CYCLE
        ),
        label text NOT NULL
      );
    `;
    const desiredSchema = `
      CREATE TABLE public.identity_updates (
        id integer GENERATED ALWAYS AS IDENTITY (
          START WITH 10 INCREMENT BY 7 MINVALUE 10 MAXVALUE 2000 CACHE 3 CYCLE
        ),
        label text NOT NULL
      );
    `;

    await executeColumnMigration(client, initialSchema, services);
    const first = await client.query(
      "INSERT INTO public.identity_updates (label) VALUES ('before') RETURNING id"
    );
    expect(first.rows[0].id).toBe(10);

    const plan = await planSchema(desiredSchema);
    const sql = plan.transactional.join("\n");
    expect(sql).toContain('ALTER COLUMN "id" SET GENERATED ALWAYS');
    expect(sql).toContain('ALTER COLUMN "id" SET INCREMENT BY 7');
    expect(sql).toContain('ALTER COLUMN "id" SET MAXVALUE 2000');
    expect(sql).toContain('ALTER COLUMN "id" SET CACHE 3');
    expect(sql).toContain('ALTER COLUMN "id" SET CYCLE');
    expect(sql).not.toMatch(/DROP (?:COLUMN|IDENTITY|SEQUENCE)/);

    await services.executor.executePlan(client, plan, true);
    const second = await client.query(
      "INSERT INTO public.identity_updates (label) VALUES ('after') RETURNING id"
    );
    expect(second.rows[0].id).toBe(17);
    expect(
      (await client.query("SELECT label FROM public.identity_updates ORDER BY id")).rows
    ).toEqual([{ label: "before" }, { label: "after" }]);
    await expect(
      client.query(
        "INSERT INTO public.identity_updates (id, label) VALUES (500, 'forbidden')"
      )
    ).rejects.toThrow(/OVERRIDING SYSTEM VALUE|generated always|non-DEFAULT value/i);
    expect((await planSchema(desiredSchema)).hasChanges).toBe(false);
  });

  test("orders range changes safely when switching from descending to ascending", function () {
    const desired: Table[] = [
      {
        name: "identity_direction",
        columns: [
          {
            name: "id",
            type: "INTEGER",
            nullable: false,
            identity: {
              generation: "ALWAYS",
              start: "1",
              increment: "1",
              minValue: "1",
              maxValue: "2147483647",
              cache: "1",
              cycle: false,
            },
          },
        ],
      },
    ];
    const current: Table[] = [
      {
        name: "identity_direction",
        columns: [
          {
            name: "id",
            type: "integer",
            nullable: false,
            identity: {
              generation: "ALWAYS",
              start: "-1",
              increment: "-2",
              minValue: "-2147483648",
              maxValue: "-1",
              cache: "1",
              cycle: false,
            },
          },
        ],
      },
    ];

    const sql = services.differ.generateMigrationPlan(desired, current)
      .transactional[0]!;
    expect(sql.indexOf("SET MAXVALUE 2147483647")).toBeLessThan(
      sql.indexOf("SET MINVALUE 1")
    );
    expect(sql.indexOf("SET INCREMENT BY 1")).toBeLessThan(
      sql.indexOf("SET MINVALUE 1")
    );
  });

  test("restores PostgreSQL defaults when explicit identity options are removed", async function () {
    const initialSchema = `
      CREATE TABLE public.identity_defaults (
        id integer GENERATED BY DEFAULT AS IDENTITY (
          START WITH 50 INCREMENT BY 5 MINVALUE 10 MAXVALUE 500 CACHE 4 CYCLE
        )
      );
    `;
    const desiredSchema = `
      CREATE TABLE public.identity_defaults (
        id integer GENERATED BY DEFAULT AS IDENTITY
      );
    `;

    await executeColumnMigration(client, initialSchema, services);
    const plan = await planSchema(desiredSchema);
    const sql = plan.transactional.join("\n");
    expect(sql).toContain('ALTER COLUMN "id" SET START WITH 1');
    expect(sql).toContain('ALTER COLUMN "id" SET INCREMENT BY 1');
    expect(sql).toContain('ALTER COLUMN "id" SET MINVALUE 1');
    expect(sql).toContain('ALTER COLUMN "id" SET MAXVALUE 2147483647');
    expect(sql).toContain('ALTER COLUMN "id" SET CACHE 1');
    expect(sql).toContain('ALTER COLUMN "id" SET NO CYCLE');

    await services.executor.executePlan(client, plan, true);
    const inspected = await services.inspector.getCurrentSchema(client);
    const table = inspected.find(function findTable(candidate) {
      return candidate.name === "identity_defaults";
    });
    expect(findColumn(table!.columns, "id")?.identity).toMatchObject({
      generation: "BY DEFAULT",
      start: "1",
      increment: "1",
      minValue: "1",
      maxValue: "2147483647",
      cache: "1",
      cycle: false,
    });
    expect((await planSchema(desiredSchema)).hasChanges).toBe(false);
  });

  test("drops identity and its implicit not-null constraint without replacing the column", async function () {
    const initialSchema = `
      CREATE TABLE public.identity_removal (
        id integer GENERATED ALWAYS AS IDENTITY,
        label text NOT NULL
      );
    `;
    const desiredSchema = `
      CREATE TABLE public.identity_removal (
        id integer,
        label text NOT NULL
      );
    `;

    await executeColumnMigration(client, initialSchema, services);
    await client.query(
      "INSERT INTO public.identity_removal (label) VALUES ('preserved')"
    );

    const plan = await planSchema(desiredSchema);
    const sql = plan.transactional.join("\n");
    expect(sql).toContain('ALTER COLUMN "id" DROP IDENTITY');
    expect(sql).toContain('ALTER COLUMN "id" DROP NOT NULL');
    expect(sql).not.toContain('DROP COLUMN "id"');

    await services.executor.executePlan(client, plan, true);
    await client.query(
      "INSERT INTO public.identity_removal (id, label) VALUES (NULL, 'nullable')"
    );
    const rows = await client.query(
      "SELECT id, label FROM public.identity_removal ORDER BY label"
    );
    expect(rows.rows).toEqual([
      { id: null, label: "nullable" },
      { id: 1, label: "preserved" },
    ]);
    expect(
      (
        await client.query(
          "SELECT to_regclass('public.identity_removal_id_seq') AS sequence_name"
        )
      ).rows[0].sequence_name
    ).toBeNull();
    expect((await planSchema(desiredSchema)).hasChanges).toBe(false);
  });

  test("renames an identity sequence transactionally while preserving its current value", async function () {
    const initialSchema = `
      CREATE TABLE public.identity_rename (
        id bigint GENERATED ALWAYS AS IDENTITY,
        label text NOT NULL
      );
    `;
    const desiredSchema = `
      CREATE TABLE public.identity_rename (
        id bigint GENERATED ALWAYS AS IDENTITY (
          SEQUENCE NAME public.renamed_identity_sequence
        ),
        label text NOT NULL
      );
    `;

    await executeColumnMigration(client, initialSchema, services);
    await client.query(
      "INSERT INTO public.identity_rename (label) VALUES ('before')"
    );

    const plan = await planSchema(desiredSchema);
    expect(plan.transactional).toContain(
      'ALTER SEQUENCE "public"."identity_rename_id_seq" RENAME TO "renamed_identity_sequence";'
    );
    expect(plan.transactional.join("\n")).not.toMatch(
      /DROP (?:COLUMN|IDENTITY|SEQUENCE)/
    );

    await services.executor.executePlan(client, plan, true);
    const inserted = await client.query(
      "INSERT INTO public.identity_rename (label) VALUES ('after') RETURNING id"
    );
    expect(inserted.rows[0].id).toBe("2");

    const inspected = await services.inspector.getCurrentSchema(client);
    const table = inspected.find(function findTable(candidate) {
      return candidate.name === "identity_rename";
    });
    expect(findColumn(table!.columns, "id")?.identity?.sequenceName).toEqual({
      schema: "public",
      name: "renamed_identity_sequence",
    });
    expect((await planSchema(desiredSchema)).hasChanges).toBe(false);
  });
});
